#cloud-config

groups:
  - students: [bob,john]

users:
  - default
  - name: bob
    primary_group: student
    groups: sudo
  - name: john
    primary_group: student
    groups: sudo

ssh_pwauth: true
chpasswd:
  expire: false
  users:
    - name: bob
      password: Init123456
      type: text
    - name: john
      password: Init123456
      type: text

