#cloud-config

ssh_authorized_keys:
 - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMA6/o8eaQchlkuzhU3sJZes4iJFHdcA/LttuxWj62/a dennis.buathong@hotmail.com

write_files:
- path: /tmp/iackey
  permissions: '0600'
  content: |
SSH-KEY-PLACE

packages:
 - git
 - ansible

runcmd:
- [ python3, -m, pip, install, ansible ]
- export GIT_SSH_COMMAND="ssh -i /tmp/iackey -o StrictHostKeyChecking=no"
- cd /home/ubuntu/
- git clone git@gitlab.com:Bazzako/iac_ansible.git
- touch /etc/cloud/cloud-init.disabled