apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: K0S Cluster Dennis
spec:
  hosts:
  - ssh:
      address: 10.0.22.14
      user: ubuntu
      port: 22
      keyPath: C:\Users\dennis.buathong\.ssh\id_rsa
    role: controller
  - ssh:
      address: 10.0.22.15
      user: ubuntu
      port: 22
      keyPath: C:\Users\dennis.buathong\.ssh\id_rsa
    role: worker
  - ssh:
      address: 10.0.22.4
      user: ubuntu
      port: 22
      keyPath: C:\Users\dennis.buathong\.ssh\id_rsa
    role: worker
  - ssh:
      address: 10.0.22.10
      user: ubuntu
      port: 22
      keyPath: C:\Users\dennis.buathong\.ssh\id_rsa
    role: worker