apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-persistent-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-storage