apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "nfs-storage"
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.0.22.8"
  share: "/data/storage/K0S Cluster Dennis"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1