#cloud-config

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMA6/o8eaQchlkuzhU3sJZes4iJFHdcA/LttuxWj62/a dennis.buathong@hotmail.com

write_files:
- path: /tmp/iackey
  permissions: '0600'
  content: |
SSH-KEY-PLACE

runcmd:
- export GIT_SSH_COMMAND="ssh -i /tmp/iackey -o StrictHostKeyChecking=no"
- git clone git@gitlab.com:Bazzako/iac_test.git
- touch /etc/cloud/cloud-init.disabled
