version: '3.9'

name: mikro-adventures-dev

networks:
  ma-net:

services:

  ma-proxy:
    container_name: ma-proxy-dev
    restart: always
    image: nginx:1.13.7
    ports:
      - 80:80
    volumes:
      - ./ma-proxy/nginx-proxy.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ma-net
    depends_on:
      - ma-frontend
      - ma-backend

  ma-frontend:
    build:
      context: ./ma-frontend
      dockerfile: 'Dockerfile'
    volumes:
      - ./ma-frontend:/app
      - /app/node_modules
    container_name: ma-frontend-dev
    networks:
      ma-net:
        aliases:
          - ma-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  ma-backend:
    container_name: ma-backend-dev
    networks:
      ma-net:
        aliases:
          - ma-backend
    restart: always
    build:
      context: ./ma-backend
    volumes:
      - ./ma-backend:/app
    environment:
      - DATABASE_URI=mysql+mysqlconnector://root:root@ma-db:3306/ma
      - CHOKIDAR_USEPOLLING=true
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
    depends_on:
      ma-db:
        condition: service_healthy

  ma-db:
    image: mysql:5.7.43
    container_name: ma-db-dev
    networks:
      - ma-net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - ma-db:/var/lib/mysql

volumes:
  ma-db: